export const IPC_CHANNELS = {
  appStatus: 'app:status',
  appUnlock: 'app:unlock',
  appLock: 'app:lock',
  appChangePassword: 'app:changePassword',
  noteList: 'note:list',
  noteGet: 'note:get',
  noteCreate: 'note:create',
  noteSaveDraft: 'note:saveDraft',
  noteMoveToTrash: 'note:moveToTrash',
  noteRestore: 'note:restore',
  noteDeleteForever: 'note:deleteForever',
  noteToggleFavorite: 'note:toggleFavorite',
  searchQuery: 'search:query',
  secretReveal: 'secret:reveal',
  historyList: 'history:list',
  historyRestore: 'history:restore',
  exportMarkdown: 'export:markdown',
  exportHtml: 'export:html',
  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  backupExport: 'backup:export',
  backupImport: 'backup:import',
  fileSaveText: 'file:saveText',
  fileOpenJson: 'file:openJson'
} as const;
